pim_datagrid_load:
    path: /{alias}/load
    defaults: { _controller: pim_datagrid.controller.datagrid:loadAction }
    requirements:
        _method: GET
        _format: json

pim_datagrid_get_filters:
    path: /{alias}/filters/{search}
    defaults: { _controller: pim_datagrid.controller.datagrid:getFiltersAction }
    requirements:
        _method: GET
        _format: json
